pipeline {
    agent { docker { image 'maven:3.3.3' } }
    stages {
        stage('Build Test Script') {
            steps {
                echo "TESTING"
                sh 'javac -d . test_script.java'
                sh 'java com.company.jenkins.test_script'

            }
        }
    }
}