# Generated by Django 3.2.8 on 2021-11-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beverages',
            fields=[
                ('beverage_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=10, max_digits=10)),
                ('alcoholic', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=10, max_digits=10)),
                ('allergens', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DrinkItems',
            fields=[
                ('drink_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('count', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('alcohol_content', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('count', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('allergens', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Loyalty',
            fields=[
                ('loyalty_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('loyalty_points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('date_created', models.DateField()),
                ('set_menu_price', models.DecimalField(decimal_places=10, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=10, max_digits=10)),
                ('two_for_one', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('user_type', models.CharField(max_length=500)),
            ],
        ),
    ]
