# Generated by Django 3.2.8 on 2021-11-02 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restuarant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_cost', models.DecimalField(decimal_places=10, max_digits=10)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Restuarant.users')),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Restuarant.users'),
        ),
    ]
