# Generated by Django 3.2.9 on 2021-11-07 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restuarant', '0003_dishes_fooditems_menuitem_orderlineitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beverages',
        ),
        migrations.RemoveField(
            model_name='dishes_fooditems',
            name='dish_id',
        ),
        migrations.RemoveField(
            model_name='dishes_fooditems',
            name='food_id',
        ),
        migrations.DeleteModel(
            name='DrinkItems',
        ),
        migrations.RemoveField(
            model_name='loyalty',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu_id',
        ),
        migrations.RemoveField(
            model_name='orderlineitems',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='orderlineitems',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Dishes',
        ),
        migrations.DeleteModel(
            name='Dishes_FoodItems',
        ),
        migrations.DeleteModel(
            name='FoodItems',
        ),
        migrations.DeleteModel(
            name='Loyalty',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='OrderLineItems',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
