# Generated by Django 3.2.9 on 2021-11-08 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restuarant', '0004_auto_20211107_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_cost', models.DecimalField(decimal_places=10, max_digits=10)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Restuarant.users')),
            ],
        ),
        migrations.CreateModel(
            name='Loyalty',
            fields=[
                ('loyalty_id', models.AutoField(primary_key=True, serialize=False)),
                ('loyalty_points', models.IntegerField()),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Restuarant.users')),
            ],
        ),
    ]
