# Generated by Django 3.2.9 on 2021-11-08 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restuarant', '0006_beverages_dishes_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkItems',
            fields=[
                ('drink_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('count', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('alcohol_content', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('count', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('allergens', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('menu_item', models.AutoField(primary_key=True, serialize=False)),
                ('Dish_Bev_id', models.IntegerField()),
                ('food', models.BooleanField()),
                ('menu_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Restuarant.menu')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItems',
            fields=[
                ('OrderLineItems', models.AutoField(primary_key=True, serialize=False)),
                ('food', models.BooleanField()),
                ('menu_item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Restuarant.menuitem')),
                ('order_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Restuarant.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Dishes_FoodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Restuarant.dishes')),
                ('food_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Restuarant.fooditems')),
            ],
        ),
    ]
