# Generated by Django 3.2.9 on 2021-11-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restuarant', '0007_dishes_fooditems_drinkitems_fooditems_menuitem_orderlineitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beverages',
            name='description',
        ),
    ]
