# Generated by Django 3.2.9 on 2021-11-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restuarant', '0009_alter_beverages_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverages',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
