# Generated by Django 3.2.9 on 2021-11-11 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restuarant', '0010_alter_beverages_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='Restuarant.users')),
                ('employee_type', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='drinkitems',
            name='alcohol_content',
        ),
        migrations.RemoveField(
            model_name='drinkitems',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fooditems',
            name='description',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
