# Generated by Django 3.2.9 on 2021-11-12 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restuarant', '0012_alter_employeesalary_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='user_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='Restuarant.users'),
        ),
    ]
