# Generated by Django 3.2.9 on 2021-11-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restuarant', '0016_auto_20211113_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='salary',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
