# Generated by Django 3.2.9 on 2021-11-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restuarant', '0018_alter_employeesalary_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverages',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
