# Generated by Django 3.2.9 on 2021-11-13 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restuarant', '0022_auto_20211113_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Restuarant.users'),
        ),
    ]
