# Generated by Django 3.2.9 on 2021-11-13 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restuarant', '0025_alter_employeesalary_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Restuarant.users'),
        ),
    ]
