# Generated by Django 3.2.9 on 2021-11-13 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restuarant', '0026_alter_employeesalary_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Restuarant.users'),
        ),
    ]
