# Generated by Django 3.2.9 on 2021-11-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restuarant', '0028_auto_20211115_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='two_for_one',
        ),
    ]
