# Generated by Django 3.2.9 on 2021-11-15 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restuarant', '0029_remove_menu_two_for_one'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='Dish_Bev_id',
            new_name='dish_bev_id',
        ),
    ]
