# Generated by Django 3.2.9 on 2021-11-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restuarant', '0030_rename_dish_bev_id_menuitem_dish_bev_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitems',
            name='food',
        ),
    ]
