# Generated by Django 3.2.9 on 2021-11-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restuarant', '0031_remove_orderlineitems_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitems',
            name='food',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
