# Generated by Django 3.2.9 on 2021-11-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restuarant', '0032_orderlineitems_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitems',
            old_name='OrderLineItems',
            new_name='orderlineitems_id',
        ),
    ]
