# Generated by Django 3.2.9 on 2022-02-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restuarant', '0033_rename_orderlineitems_orderlineitems_orderlineitems_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverages',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
