# Generated by Django 3.2.9 on 2022-02-18 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restuarant', '0035_auto_20220218_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitems',
            old_name='Order_id',
            new_name='order_id',
        ),
    ]
