# Generated by Django 3.2.9 on 2022-02-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restuarant', '0036_rename_order_id_orderlineitems_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_item',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
