# Generated by Django 3.2.9 on 2022-02-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restuarant', '0037_menu_menu_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_item',
            new_name='menu_items',
        ),
    ]
