# Generated by Django 3.2.9 on 2022-02-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restuarant', '0038_rename_menu_item_menu_menu_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='Allergens',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
