# Generated by Django 3.2.9 on 2022-03-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restuarant', '0039_menuitem_allergens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_items',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
