---
- hosts: localhost
  vars:
    accountInfo: "{{ lookup('file', 'accountInfo.json') }}"


  tasks:
    - name: Set Var
      set_fact:
        username: "{{ item.username }}"
        email: "{{ item.email }}"
      loop: "{{ accountInfo }}"

    - name: Create Password
      shell: python3 generatePassword.py
      register: generatedPassword
    
    - name: Add Password to User Details 
      expect:
        command: python3 addPasswordToJson.py
        responses:
          'Enter Username:': "{{ username }}"
          'Enter Email:': "{{ email }}"
          'Enter Password:': "{{ generatedPassword['stdout_lines'][0] }}"
          
    - name: E-mail Password
      mail:
        host: smtp.gmail.com
        port: 587
        username: thedreamteamandmatt@gmail.com
        password: dreamteam101
        to: "{{ email }}"
        subject: Account Password
        body: "Welcome to The Dream Team and Matts Diner {{ username }} \n\n 
        This is your accounts password {{ generatedPassword['stdout_lines'][0] }} "
      delegate_to: localhost